SELECT COUNT(1) FROM ly_lawyer;
UPDATE ly_lawyer t SET t.`gender` = 'MALE' ;
UPDATE ly_lawyer t SET t.`status` = 'Y' ;

CREATE TABLE `ly_lawyer` (
  `id` BIGINT(15)  PRIMARY KEY AUTO_INCREMENT,
  `lawfirm` BIGINT(15) DEFAULT NULL,
  `name` VARCHAR(60) DEFAULT NULL,
  `mobile` VARCHAR(20) DEFAULT NULL,
  `gender` VARCHAR(10) DEFAULT NULL,
  `telephone` VARCHAR(20) DEFAULT NULL,
  `email` VARCHAR(60) DEFAULT NULL,
  `age` BIGINT(3) DEFAULT NULL,
  `level` VARCHAR(10) DEFAULT NULL,
  `working_years` BIGINT(15) DEFAULT NULL,
  `degree` VARCHAR(10) DEFAULT NULL,
  `university` VARCHAR(60) DEFAULT NULL,
  `status` VARCHAR(10) DEFAULT NULL,
  `create_date` DATE DEFAULT NULL,
  `last_modify_date` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8  AUTO_INCREMENT = 1000000 ;


CREATE TABLE `ly_user` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `user_name` VARCHAR(32) NOT NULL COMMENT '用户名',
  `password` VARCHAR(60) DEFAULT NULL COMMENT '密码',
  `real_name` VARCHAR(60) DEFAULT NULL COMMENT '真是姓名',
  `salt` VARCHAR(60) DEFAULT NULL COMMENT '盐',
  `verify_code` VARCHAR(60) DEFAULT NULL COMMENT '验证码',
   `mobile` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(20) DEFAULT NULL COMMENT '邮箱',
  `status` VARCHAR(20) DEFAULT NULL COMMENT '状态',
  `image_url` VARCHAR(20) DEFAULT NULL COMMENT '头像地址',
  `birthday` DATETIME DEFAULT NULL COMMENT '出生日期',
  `create_time` DATETIME DEFAULT NULL COMMENT '创建时间',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`user_id`)
) ENGINE=INNODB AUTO_INCREMENT=1000000 DEFAULT CHARSET=utf8